### ISSUE TITLE
Reported as malware by several antivirus

### ISSUE THREAD

**Issue by pierrecoach** [portapps/postman-portable#1]
![postman-portable-malware](https://user-images.githubusercontent.com/5269604/38361910-47b0bb5a-38cf-11e8-9f4e-5123c373eaa7.png)

**Comment by crazy-max** [comment]
As i said [in an other project](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker), detections found by VirusTotal scan are generic. Most likely based on a heuristic detection. Heuristics are more prone to false-positive detections.

This [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to [report this](https://github.com/crazy-max/WindowsSpyBlocker/issues/82#issuecomment-337611345) to your Antivirus software vendor.

I have sent the file to BitDefender and F-Secure and they said it's a false positive : https://www.virustotal.com/#/file/9444559fa3c0a1f282dd5bdbb742c0ecdbd8a677a154861056e58dd8e149c101/detection

![image](https://user-images.githubusercontent.com/1951866/38365233-d67bd200-38db-11e8-9bce-e3bc9906de36.png)
