### ISSUE TITLE
Virus detected on last release

### ISSUE THREAD

**Issue by chechsp** [portapps/postman-portable#18]
#### Steps to reproduce this issue

1. Go to releases
2. Click [Virustotal link](https://www.virustotal.com/gui/file/e23589621bc855ba4fb68506233bb65430038f7ec68c1b67ddc2caa40e55d72d/detection) for Windows 64 bit download
3. Voilà

#### Expected behaviour

> No virus should be detected

#### Actual behaviour

> 3 engines detect a virus

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 7.26.1-39

**Operating system** : Windows 64 bits

**Comment by crazy-max** [comment]
Sometimes Antivirus scanner reports that a program is infected with a Virus or Trojan, even when the program is not really infected with any malicious code. This kind of problem is known as "False Positive". In other words, [Antivirus companies cause a big headache to small developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).

As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive and this [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor as a false positive.
