### ISSUE TITLE
Lost all my collections after first run

### ISSUE THREAD

**Issue by geri777** [portapps/postman-portable#3]
I had Postman client installed on my PC. When I opened the portable version I lost all my collections. 
Maybe you should warn when running the app the first time.

**Comment by crazy-max** [comment]
Hi @geri777, can you read and apply the [SUPPORT page](https://github.com/portapps/postman-portable/blob/master/.github/SUPPORT.md) please ? (specially logs)

**Comment by geri777** [comment]
Hi, thank you for getting back to me! Please find the requested information below.

### Behaviour
Loading Postman-Portable will remove collections from already installed Postman apps.

#### Steps to reproduce this issue

1.  Install Postman from https://www.getpostman.com/apps (64 bits, latest version 6.1.4)
2. Add collection(s) and request(s)
5. Close application

6. Install/Copy Postman-Portable
7. Start Application and add new collections/requests
8. Close Application

9. Start standard Postman application (not the portable one)
10. Verify if you still have your saved collections in the standard application

#### Expected behaviour

> Postman Portable should not corrupt the collection store

### Configuration

Operating system: Windows 8.1 Pro 64 bits

### Logs

https://justpaste.it/3xi2v

**Comment by crazy-max** [comment]
Your use case is abnormal. If you have moved data from `%APPDATA%\Postman\*` to `D:\temp\postman-portable\data` and try to launch the standard app again, it is normal that your collections are no longer available. If you want to use both the portable application and the installed application, either duplicate the data or use a symbolic link.

**Comment by geri777** [comment]
I have not done anything like that - I have not moved anything! I have just installed the portable version.

**Comment by crazy-max** [comment]
Oh ok, i thought you have followed the steps here : https://portapps.github.io/app/postman-portable/#installation

**Comment by crazy-max** [comment]
I can't reproduce your problem. From what I can see, history, collections, requests and environments are saved in the local storage AND in your account. But if you logout your local storage is clear :

![image](https://user-images.githubusercontent.com/1951866/46064989-33d71900-c171-11e8-9615-7975d4024d69.png)
