### ISSUE TITLE
Trojan infestation identified by Windows Defender

### ISSUE THREAD

**Issue by ab-cc** [portapps/postman-portable#35]
Hello Team,

Windows Defender has flagged the latest 32-bit postman-portable as dangerous due to presence of Trojan: Win32/Zpevdo.B

![image](https://user-images.githubusercontent.com/45005187/110831356-2a4db700-82c0-11eb-816b-658230f51b37.png)

**Comment by crazy-max** [comment]
@ab-cc https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper

**Comment by ab-cc** [comment]
Thank you for clarifying this, what's surprising is that the 64-bit executable was not flagged by defender, only the 32-bit executable was flagged 🙄
