### ISSUE TITLE
[win32 6.2.4] screen goes black after several tab switches

### ISSUE THREAD

**Issue by m3dbedb** [portapps/postman-portable#4]
* OS: win7 32 bit.
* Video: intel HD 2000 (driver from 26.05.2015).
* Screen scale: 125%.
* Res: 1920x1080.
* Simple graphics mode: enabled.

Same bug as in postmanlabs/postman-app-support#2833 version :

> Picture in the middle of...

![image](https://user-images.githubusercontent.com/1951866/44720428-17d74d80-aac7-11e8-96f5-f107521475c7.png)

> ...a collapsible block

**Comment by crazy-max** [comment]
@m3dbedb I have reformatted your post.. As it's an upstream issue, I can't do anything about it. I have subscribed to it anyway.
