### ISSUE TITLE
9.27.0 Fails to Execute

### ISSUE THREAD

**Issue by Major-Mike** [portapps/postman-portable#49]
The latest version does not work, each time you execute you get:

![image](https://user-images.githubusercontent.com/55165479/189820306-31338425-01db-4579-8779-d6271efd9bd9.png)

**Comment by crazy-max** [comment]
Can't repro:

![image](https://user-images.githubusercontent.com/1951866/193919166-96301032-2e00-4784-a216-c9144d238863.png)

Also can't help without a proper [bug report](https://github.com/portapps/postman-portable/issues/new?assignees=&labels=&template=bug_report.md), sorry.

**Comment by Major-Mike** [comment]
Wow, screenshot, happens by simply running the app and you need more. Yes, lazy has been completed. Your "proper" report wasn't there when I submitted this, so you need to know something, ask.
