### ISSUE TITLE
Q: How to find out full request path if base uri is stored as environment variable

### ISSUE THREAD

**Issue by kinekt4** [portapps/postman-portable#5]
### Behaviour

If the base uri is stored as environment variable, it is difficult to determine what the full request path was.

This is also compounded by the fact that environment variables can be over-ridden with "Current Value" over the "Initial Value"

#### Steps to reproduce this issue

1. Create a base uri as an environment variable for your request. eg. base_uri
2. Set "Initial value" to: https://test-base-uri.com
3. Set "Current Value" to https://base-uri.com
4. Create new request: GET {{base_uri}}/rest/request1
5. Send Request

#### Expected behaviour

There should be somewhere I can verify what the actual full request URI was after the the request was sent.

Like devtools on most browsers, this information is displayed in the "Headers" tab of the request before any header information is displayed. Eg.

    Request URL: https://base-uri.com/rest/request1
    Request method: GET
    Remote address: 192.168.128.1
    Status code: 200
    Version: HTTP/1.1
    
    ...
    Content-Type: application/json
    ...

#### Actual behaviour

* There's nowhere in the interface that would definitively tell me what the full request path is.
* You can deduce what it is by clicking on environment variables and checking

### Configuration

Postman for Windows
Version 6.3.0
win32 10.0.17134 / x64

Windows 10 Pro 64 bits
Version 1803

**Comment by crazy-max** [comment]
I don't understand your problem with the portable version of Postman. I think you've got the wrong repository: https://github.com/postmanlabs/postman-app-support/issues
