### ISSUE TITLE
Why it is not updated to latest build?

### ISSUE THREAD

**Issue by sfksuperman** [portapps/postman-portable#52]
Why this portable version is not updated to latest build?

**Comment by thinhdnn** [comment]
I submitted a pull request for v10.15.0. Will wait a approval

**Comment by sfksuperman** [comment]
> I submitted a pull request for v10.15.0. Will wait a approval

Thanks for this (even though it took almost 3 months for you to reply 😝).
Bdw tell me this, my org has restricted Postman to update through its network. Could you plz tell me which link should I put in my proxy settings so that my system can bypass and allow it to download and install postman updates manually and/or automatically?

**Comment by crazy-max** [comment]
> Thanks for this (even though it took almost 3 months for you to reply 😝).

This is an open source project. Contribs welcomed.
