### ISSUE TITLE
Installed latest version but get error while opening the postman app

### ISSUE THREAD

**Issue by sfksuperman** [portapps/postman-portable#55]
I installed the latest version 10.15.0-57 on top of existing older version 10.8.0-56 as mentioned in the upgrade steps, check screenshot below:

![image](https://github.com/portapps/postman-portable/assets/34414624/00a2b39a-79a4-4b14-9cc2-de4dde684080)

Installation done successfully but when I try to open the app, it gives below error:

![image](https://github.com/portapps/postman-portable/assets/34414624/a02b8e7a-38e5-48cb-b769-e762ea2f10f3)

Please tell me what to do next. Thanks.

**Comment by crazy-max** [comment]
Can't help without proper [bug report](https://github.com/portapps/postman-portable/issues/new?assignees=&labels=&projects=&template=bug_report.md).
