### ISSUE TITLE
Installed 10.15.0-57 but it says 7.9.0

### ISSUE THREAD

**Issue by sfksuperman** [portapps/postman-portable#56]
I installed the latest version 10.15.0-57 but when I open the postman app's setting, it says it's 7.9.0 version. Why?

![image](https://github.com/portapps/postman-portable/assets/34414624/c1048873-cdc4-4b3a-a85b-767a3711ef24)

**Comment by sfksuperman** [comment]
Still waiting for acknowledgment and reply.

**Comment by crazy-max** [comment]
Can't repro. 10.15.0-57 is Postman 10.15.0: https://github.com/portapps/postman-portable/actions/runs/5496380160/jobs/10016368909#step:12:225

![image](https://github.com/portapps/postman-portable/assets/1951866/db1052ed-9b53-4f71-bda5-6e33309b53da)
