### ISSUE TITLE
Update failing, even manual update.

### ISSUE THREAD

**Issue by sfksuperman** [portapps/postman-portable#57]
Installed 10.15.0-57 Postman and tried updating both automatic and manual, but keeps on failing. Screenshots below:

<img width="620" alt="image" src="https://github.com/portapps/postman-portable/assets/34414624/c59174c4-06b7-4bb7-a97c-d1160e76c6a0">

<img width="449" alt="Screenshot 2023-07-16 230327" src="https://github.com/portapps/postman-portable/assets/34414624/5b15f67f-5090-4ba9-80e0-3efa2ee340a8">

**Comment by crazy-max** [comment]
> Installed 10.15.0-57 Postman and tried updating both automatic and manual, but keeps on failing.

We don't support auto update from the app itself. You need to wait for it to be released on Portapp website. Also we can't disable update notifications atm unfortunately: https://github.com/postmanlabs/postman-app-support/issues/6999
