### ISSUE TITLE
postman-portable.sample.yml file does not grant standard user write permissions

### ISSUE THREAD

**Issue by troogyt** [portapps/postman-portable#58]
### Behaviour
Downloaded and unzipped `postman-portable-win64-10.15.0-57.7z` into `C:\Program Files\Postman-Portable\`.
This has to be done as Administrator in order to write to `C:\Program Files\`.
Created a Desktop Shortcut to `"C:\Program Files\Postman-Portable\postman-portable.exe"` under `C:\Users\Public\Desktop\`.

When I try launching postman-portable.exe, either by clicking the shortcut or the exe directly, it is blocked due to insufficient permissions on the `postman-portable.sample.yml` file. I suspect the exe needs to be able to modify/write to that file.

I think there will be a few permissions issues that need to be sorted.

To resolve this, I think we need to look at what all the permissions required are on the `Postman-Portable` main folder that would allow any user who wants to run it would need. Need to account for any files or app sub-folders that get created, written to or deleted.

#### Steps to reproduce this issue

1. Unzip `postman-portable-win64-10.15.0-57.7z` into `C:\Program Files\Postman-Portable\` as the local Administrator
2. [Optionally] create shortcut to `postman-portable.exe` on [Public or User] Desktop
3. Try to launch `postman-portable.exe` via shortcut or directly.

#### Expected behaviour

> It should run without error

#### Actual behaviour

> It is blocked due to insufficient permissions on YAML file.

### Configuration

Windows 11 Home 64 bit

### Screenshots

![image](https://github.com/portapps/postman-portable/assets/41710820/126aac23-d73a-4d23-9f37-2dca29e2efc0)

**Comment by troogyt** [comment]
Changing permissions on `Postman-Portable` folder from:
![image](https://github.com/portapps/postman-portable/assets/41710820/e3886dda-abe1-488a-91da-52ef5fad470d)

to:
![image](https://github.com/portapps/postman-portable/assets/41710820/b11326a8-36ff-4afb-b6b7-9b7dadf3f00c)

did not work. After this I kept getting an error stating `Electron main path does not exist with prefix 'app-' in C:\Program Files\Postman-Portable\app`. This is beyond me, though.

So...not very portable yet...

**Comment by crazy-max** [comment]
Not sure how this happens, I can't repro on fresh Windows machine.
