### ISSUE TITLE
Parameter --disable-remote-fonts is not passed from postman-portable.exe to postman.exe?

### ISSUE THREAD

**Issue by exec228** [portapps/postman-portable#59]
#### Steps to reproduce this issue

1. Run postman-portable.exe --disable-remote-fonts
2. Look at UI

#### Expected behaviour

> Expected Windows fonts, not that bad Inter font

#### Actual behaviour

> Inter font all over UI

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : postman-portable-win64-10.8.0-56.7z

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10x64 22H2 19045.3208

### Screenshots

https://i.imgur.com/rQaCQMH.png

**Comment by crazy-max** [comment]
Set the flags in `postman-portable.yml` config file (`args`): https://portapps.io/doc/configuration/
